name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.7"

    - name: Build
      run: make build
    
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
      with:
        version: 'latest'

    - name: Test
      run: make tests

    - name: Lint
      run: make lint
